#!/bin/zsh
HOME_DIR=$(cd "$(dirname "$0")"/..;pwd)
cd $HOME_DIR
echo "Start building simulation environment..."
rm -rf obj_dir
verilator --trace --cc --exe --build -j -Irtl/include --top-module top rtl/**/*.sv rtl/sim/sim_main.cpp >/dev/null
if [ $? -eq 0 ]; then
  echo "Build successfully!"
else
  echo "Build failed!"
  exit 1
fi
echo "Start running simulation..."
./obj_dir/Vtop
