#!/bin/zsh
HOME_DIR=$(cd "$(dirname "$0")"/..;pwd)
cd $HOME_DIR
echo "Start building simulation environment..."
rm -rf obj_dir
verilator --trace --cc --exe --build -j --top-module top rtl/lib/gelato_fifo.sv rtl/test/fifo/top.sv rtl/test/fifo/test_fifo.cpp >/dev/null
if [ $? -eq 0 ]; then
  echo "Build successfully!"
else
  echo "Build failed!"
  exit 1
fi
echo "Start running simulation..."
./obj_dir/Vtop
